### ISSUE TITLE
How can I improve it?

### ISSUE THREAD

**Issue by bensoy** [laurenorsini/caaaaarbs#1]
I want to use this extension to improve my surfing experience. What should I do to make it work like this:

Extension detects string in page: `steam://loremipsum`
Transforms it to a link like: `<a href="steam://loremipsum"> steam://loremipsum </a>` (*loremipsum* part is a variable, it should detect string from steam:// to next space character.

Is it possible? It reminds me how **Skype Click to Call** works but I don't have enough knowledge to do this kind of query & transform. 

I would be very happy if you can help me or show me a way to do it. Thanks a lot!

**Comment by laurenorsini** [comment]
Sorry, I'm not sure how I would do that. I would take to the person who created the original fork of this project, Cloud to Butt, which is credited in my Readme. Hope that helps!

**Comment by bensoy** [comment]
Thank you, I will ask to him right now :blush:
